services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}